wrist:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005
  position_only_ik: true
first_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  maxIterations: 100
  epsilon: 0.001
  lambda: 0.01
  tip_name: fftip
middle_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  maxIterations: 100
  epsilon: 0.001
  lambda: 0.01
  tip_name: mftip
ring_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  maxIterations: 100
  epsilon: 0.001
  lambda: 0.01
  tip_name: rftip
little_finger:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  maxIterations: 100
  epsilon: 0.001
  lambda: 0.01
  tip_name: lftip
thumb:
  kinematics_solver: hand_kinematics/HandKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  maxIterations: 100
  epsilon: 0.001
  lambda: 0.01
  tip_name: thtip
