sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /camera/depth_registered/points
   max_range: 2.5
   frame_subsample: 1
   point_subsample: 2
   shape_padding: 0.03
   shape_scale: 1.0
   filtered_cloud_topic: /filtered
   padding_offset: 0.03
   padding_scale: 1.0
